import type { Metadata } from "next";
import { Space_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/common/theme-provider";
import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures text is visible while the font loads
  weight: ['400', '700'], // Specify the weights you need
  variable: '--font-poppins', // Define a CSS variable for Tailwind or CSS modules
})

const spaceMono = Space_Mono({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures text is visible while the font loads
  weight: ['400', '700'], // Specify the weights you need
  variable: '--font-space-mono', // Define a CSS variable for Tailwind or CSS modules
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${poppins.variable} ${spaceMono.className}`}>
      <body
        className={`antialiased`} //${geistSans.variable} ${geistMono.variable} 
      >
        <ThemeProvider>
          {children}
          <Toaster position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
